spring:
  datasource:
    password: Test123___
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sp_gsunis?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: test
